---
- hosts: "{{ group }}"
  vars:
    package: httpd
  tasks:
    - name: "Installing {{ package }} Package"
      yum:
        name: "{{ package }}"
        state: latest
#      notify: "Starting {{ package }} Service"
    
#  handlers: 
    - name: "Starting Service"
      service:
        name: "{{ package }}"
        state: started
        enabled: yes
#      listen: "Starting {{ package }} Service" 
#      register: serv_status

#    - debug: msg="{{ serv_status }}"
