---
- hosts: "{{ group }}"
  tasks:
    - name: "Creating users"
      user:
        name: "{{ item }}"
        state: present
      with_items:
        - user1
        - user2
        - user3
