---
- hosts: "{{ group }}"
  tasks:
    - name: "Creating users"
      user:
        name: "{{ items }}"
        state: absent
      with_items:
        - user1
        - user2
        - user3
